### ISSUE TITLE
Infobox wrong / missing description Wrapper

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#29]
Comment below which items infoboxes are inaccurate. This is here to provide an overview about which wiki pages don't correctly interact with SETS.

**Comment by Shinga13** [comment]
Tilly's shield displays description of a singularity core in addition to its usual description;
Kobayashu Maru Transponder has formatting issues / too large for the Infobox

**Comment by nehpetsca** [comment]
Tilly's should be repaired now -- any more extraneous additions below the appropriate description should be fixed due to a wiki template update.  Some wiki pages may need a null edit to bump the cache if they still show excess description.

Will address the Maru as part of the actual infobox updating.
