### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#65]
Loading screen does not adapt to window size

**Comment by nehpetsca** [comment]
Slight correction: The loading screen will adapt to the known window size, but as a separate window [currently] it depends on cached window sizes and a couple natural TK window updates occur without caching still. The splash itself will be added into the main window frames in a near-future update, which will remove that specific issue.

This issue is still valid as improving the moments we cache window-shape without forcing out-of-order updates would still be desired for other sub-window alignments.

**Comment by nehpetsca** [comment]
Splash screen converted to inline frame.  No other active resizing subwindows at this time.
